### ISSUE TITLE
How to learn from you're book?

### ISSUE THREAD

**Issue by linkin-park** [Hemant-Jain-Author/Problem-Solving-in-Data-Structures-Algorithms-using-Java#1]
How to learn from the book , bought you're book {Problem-Solving-in-Data-Structures-Algorithms-using-Java} but unsure how to learn from it . 
Should i need to consider it as Q & A.

or should i need to return back to Amazon?

**Comment by Hemant-Jain-Author** [comment]
This book is for preparing for programming interview. In the start of book their is a chapter which talk about how to use this book.
