### ISSUE TITLE
Solutions to exercises

### ISSUE THREAD

**Issue by adjiandov** [Hemant-Jain-Author/Problem-Solving-in-Data-Structures-Algorithms-using-Java#2]
Hello I am following your book and I would like to know where can I find the solutions for the exercises. In the book it states that I should first attempt to solve them on my own before going to the solutions. But I cannot find any solutions to the exercises.

Thank you

**Comment by linkin-park** [comment]
solution for which chapter?
Are you looking for solution or correctness of the solution?
PS There is no explanation for solution , only code.

**Comment by Hemant-Jain-Author** [comment]
All the problems (solved examples) in the book you should first try to solve them then look for solution.

**Comment by Hemant-Jain-Author** [comment]
next edition is coming with all requests/comments incorporated. 

still solution of exercise is not yet published.
